spring:
  application:
    name: springcloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouxingxingtongxue/springcloud.git
          search-paths: spring-config
          username: zhouxingxingtongxue
          password: liaoJIAwei118312

server:
  port: 9999

# git管理配置