spring:
  application:
    name: springcloud-config

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liaoJIAwei/springcloud.git
          search-paths: config-repo
          # 私有仓库需要填写
          # username: zhouxingxingtongxue
          # password: liaoJIAwei118312

server:
  port: 9999

# git管理配置