spring:
  application:
    name: eureka-server2

server:
  port: 1002

eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server1:1001/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000


